### ISSUE TITLE
Missing wait_for_update parameter in the setDefaultConsentState calls.

### ISSUE THREAD

**Issue by philpott** [cybotcorp/gtm-templates-cookiebot-cmp#2]
https://github.com/cybotcorp/gtm-templates-cookiebot-cmp/blob/068dba0af02f19e9c47db41af5a54ce689f624f8/template.tpl#L187

I was reviewing this template and noticed that [wait_for_update](https://developers.google.com/tag-manager/templates/api#setdefaultconsentstate) was not specified in the setDefaultConsentState call. It is a best practice to include that as well so that tags that use the API's to monitor consent can possibly defer firing those few hundred millis until consent has a possiblity to resolve.

Thanks!
Michael

**Comment by bjorngronbaek** [comment]
Thank you for the input @philpott. We'll take a look shortly and make an update.

**Comment by joakim973** [comment]
Would love to have this one fixed as well :)

Thanks!

**Comment by bjorngronbaek** [comment]
This issue has be resolved. The wait_for_update parameter is now used with a default value, and it is possible to set the value through the Tag Manager.

**Comment by philpott** [comment]
Thanks!
