### ISSUE TITLE
GTM Template: Cookiebot CMP - EU CDN

### ISSUE THREAD

**Issue by vrill** [cybotcorp/gtm-templates-cookiebot-cmp#21]
https://github.com/cybotcorp/gtm-templates-cookiebot-cmp/blob/bbdada961c85e939de05bf094aa9ccbd348f9168/template.tpl#L385

Using the `.com` CDN (Akamai) is against our internal policies, and as such we cannot use the template as-is. A template, or explicit option, solely utilizing the `.eu` CDN (BunnyWay) would solve this issue for us, and I suspect many other EU vendors.

Would you agree to this being a useful addition, and to some even a necessity for continued use of CookieBot?

**Comment by Soreg** [comment]
Hey Vrill, sorry for the (very) late reply. I'll make a dedicated effort to reply faster in the future 🙂.

I agree that this is a useful and necessary addition, and want to let you know that we are planning on adding this soon - probably within a week or so.

**Comment by Soreg** [comment]
The changes has just been released, and should be visible on the template soon.
I'll close this ticket 👍
