### ISSUE TITLE
Problem with save cookiebot id in tag manager google platform

### ISSUE THREAD

**Issue by candypiotr** [cybotcorp/gtm-templates-cookiebot-cmp#37]
When entering the cookiebot template in the tag manager I get errors in the console and I can't change the cookiebot id in any way (it doesn't save this value and is still empty). Below is the error dump from the console:

![Zrzut ekranu 2024-06-24 o 09 59 40](https://github.com/cybotcorp/gtm-templates-cookiebot-cmp/assets/110376589/bbbcedc6-1cfc-4413-b9f5-0a90fd6f8347)

**Comment by Soreg** [comment]
I'm guessing this happens on the website where the template is implemented, and not when you add or update the GTM template? .. I just wanted to be sure here 🙂.

The error (infdig) is documented on [AngularJS's own documentation](https://docs.angularjs.org/error/$rootScope/infdig), and looks to be related to infinite loops. Can you verify that the site works if you remove (or pause) the Cookiebot GTM template?

**Comment by candypiotr** [comment]
Yes, the template is already added. On other pages in GTM, I've now noticed that when I go to edit the cookiebot template, these IDs are also blank, and they were filled in before for sure

**Comment by Soreg** [comment]
Hmm, that sounds odd. Can you try updating the template in an incognito tab, just to be that sure it's not some extension causing the issue?

**Comment by candypiotr** [comment]
I'll also add a picture of what it looks like when I enter the ID and try to run the code
![Zrzut ekranu 2024-06-24 o 09 25 44](https://github.com/cybotcorp/gtm-templates-cookiebot-cmp/assets/110376589/4e6ca219-c730-4dac-b2a9-8aa2570be937)

**Comment by candypiotr** [comment]
I do not see any updates for this domain, it seems that everything is up to date

**Comment by candypiotr** [comment]
Successfully created a tag on another device. You can close

**Comment by Soreg** [comment]
Ah, perfect. Glad it was resolved. I'll close the ticket 👍
