### ISSUE TITLE
GTM use of Cookiebot CMP Template doesn't work

### ISSUE THREAD

**Issue by Chrissi666** [cybotcorp/gtm-templates-cookiebot-cmp#8]
Hi there,
 I'm not able to add the Cookiebot ID to the GTM template editor (->error message: "The value must not be empty." so, how funny is that?!)
and also under "Wait for update" with the default! value of 2000 (same error message as above)

What is going on there? 
I implemented everything else like it should be. 

Any ideas?

Thanks

**Comment by oebilgen** [comment]
I see the same issue. Is anybody from the Cookiebot team here reviewing the issues?

**Comment by danieljohannsen** [comment]
Thank you for you feedback. This seems to be a temporary issue with the GTM editor itself, which has been resolved.
