### ISSUE TITLE
GTM Consent Mode - Incompatibility

### ISSUE THREAD

**Issue by twslade** [cybotcorp/gtm-templates-cookiebot-cmp#9]
Hi Cookiebot team,

Our team at Elevar have been working extensively with consent mode in GTM. We've found that most CMPs aren't designing their GTM web templates in a way that is compatible with GTM making our merchants lose many hits that should be going to marketing channels.

From Google's [Docs](https://support.google.com/tagmanager/answer/10718549?hl=en)

> The Consent Initialization trigger is designed to help you ensure that all consent settings are honored before any other triggers fire. The Consent Initialization trigger is used for tags that set or update the user consent state for your site, such as a consent management platform tag or tags that set consent defaults.

The problem I see with the current solution:
1. User visits homepage. Consent initialization fires with default state (assume everything is denied) https://github.com/cybotcorp/gtm-templates-cookiebot-cmp/blob/d534d8850b4caeb9b2c28b68c1c1eb41734ff90a/template.tpl#L204-L211
2. User "Allows all". Cookiebot consent update fires
3. User clicks to another page.
4. Consent initialization fires with default state as it did in 1
5. Data layer pushes occur. Many of the configured tags in GTM do not fire because they fail the consent test which actually isn't the user's choice.
6. Cookiebot Consent update fires

There is a timing issue here. Any persisted consent across page loads should be fired on consent initialization instead of arbitrarily firing depending on load.

I see a few paths forward here:
- We will manage our own version of this cookiebot template that utilizes cookiebot's cookies to initialize consent properly.
- We will manage another tag that reads the cookiebot cookies above and sets consent
- We can create a PR to fix this issue.

**Comment by ammonialime** [comment]
Having the same issue. From my interpretation of the Google docs on Consent Mode (referenced above) the consent type values should be set on Consent Initialization. Delaying this causes some pretty serious structural issues for complex containers and greatly increases complexity.

**Comment by danieljohannsen** [comment]
Thank you for your feedback! The timing issue is resolved in the latest version of the Cookiebot CMP template by adopting the GTM updateConsentState API and updating consent preferences immediately from the consent cookie, if it exists.
